ENV: dev
REGION: ${self:custom.region}
DYNAMO_TABLE_BOOKMARK: ${self:custom.dynamo-bookmark-name}
DYNAMO_TABLE_TAG: ${self:custom.dynamo-tag-name}
SQS_QUEUE_BOOKMARK: ${self:custom.sqs-bookmark-name}
CONFIG_DYNAMODB_ENDPOINT: ${self:custom.endpoints.dynamodb-url}
OAUTH_REDIRECT_URL: https://zetis3394f.execute-api.us-east-2.amazonaws.com/dev/callback
OAUTH_REALM: firstthumb.auth0.com
