ENV: dev
REGION: ${self:custom.region}
DYNAMO_TABLE_BOOKMARK: ${self:custom.dynamo-bookmark-name}
DYNAMO_TABLE_USER: ${self:custom.dynamo-user-name}
SQS_QUEUE_BOOKMARK: ${self:custom.sqs-bookmark-name}
CONFIG_DYNAMODB_ENDPOINT: ${self:custom.endpoints.dynamodb-url}
OAUTH_REDIRECT_URL: https://api.booklog.link/callback
OAUTH_REALM: firstthumb.auth0.com
GOOGLE_CLIENT_ID: ${self:custom.clientId}
GOOGLE_CLIENT_SECRET: ${self:custom.clientSecret}
OAUTH_KEY: ${self:custom.oauthKey}
