on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev
name: Deploy master branch
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.13.1"
      - name: Check out code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: npm install serverless-offline serverless-domain-manager serverless-puresec-cli --save-dev
      - name: Build
        run: make build
      - name: Create secret env file
        run: |
          cat > secrets.yml << EOF
          clientId: ${{ secrets.GOOGLE_CLIENT_ID }}
          clientSecret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          oauthKey: ${{ secrets.OAUTH_KEY }}
          EOF
      - name: serverless deploy
        uses: serverless/github-action@master
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
